### ISSUE TITLE
deviceToken undefined in iOS build

### ISSUE THREAD

**Issue by hvalls** [cranberrygame/cordova-plugin-pushnotification-parse#2]
Hi, I'm building my app for iOS devices by Intel XDK. Device is registered properly to Parse but the deviceToken is undefined. So I can't send push notifications. I hope you can help me, thanks.

**Comment by cranberrygame** [comment]
@bigdestroyer 

Did you set .p12 file?
If not, try this: https://github.com/cranberrygame/cordova-plugin-pushnotification-parsepushnotification#ios

Thanks

**Comment by kimulus** [comment]
I have the same problem over here device token is empty but registered on PARSE (I can see I with their admin tools, http://screencast.com/t/otguDK2erH)

I am running latest version of cordova (5.3.3) xCode 7.1 iOS 9.1

Thanks

**Comment by sekocit** [comment]
Hello! I have the same problem that no devicetoken on parse table? Did you solved it? (Also I use Intel XDK)

**Comment by solange** [comment]
Same problem here, 
I also added an 'NSLog(@"device token: %@", newDeviceToken);' on line 192 of the plugin m file, inside 
     - (void)swizzled_application:(UIApplication *)application didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)newDeviceToken

but that NSLog never gets called.

**Comment by chanat** [comment]
I got the same problem. I got onRegisterAsPushNotificationClientSucceeded but the installation object does not contain device token (empty).

**Comment by raiseisback** [comment]
same here. Cordova + Xcode. Tested on iOs 7
the device is registered in parse.com but the devicetoken is undefined

**Comment by Giabanga** [comment]
+1
